export const FETCH_INGRIDIENTS = 'FETCH_INGRIDIENTS';
export const INGREDIENT_DETAILS = 'INGREDIENT_DETAILS';
export const DELETE_INGREDIENT_DETAILS  = 'DELETE_INGREDIENT_DETAILS';
export const TAB_BUN = 'TAB_BUN';
export const TAB_SAUSE = 'TAB_SAUSE';
export const TAB_MAIN = 'TAB_MAIN';
export const  UPDATE_CONSTRUCTOR = 'UPDATE_CONSTRUCTOR';